name: 仓库自动保活｜防止定时Workflow禁用
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  keep_alive_task:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
      - name: 自动生成续命提交
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 45
